DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS tags;
DROP TABLE IF EXISTS notes_tags;


CREATE TABLE user(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	username TEXT UNIQUE NOT NULL,
	email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL	
);

CREATE TABLE notes(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	title TEXT NOT NULL,
	body TEXT ,
	user INTEGER NOT NULL,
	FOREIGN KEY (user) REFERENCES user (id)	
);

CREATE TABLE tags(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	tag TEXT NOT NULL,
	user INTEGER NOT NULL,
	FOREIGN KEY (user) REFERENCES user (id)
);

CREATE TABLE notes_tags(
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	tag INTEGER NOT NULL,
	note INTEGER NOT NULL,
	FOREIGN KEY (tag) REFERENCES tags(id),
	FOREIGN KEY (note) REFERENCES note(id)
);